
# ------------------------- MOT20 Dataset train or test spilt -------------------------
data_path: './datasets/MOT20'
train_seqs: ['01', '02', '03', '05']
test_seqs: ['04', '06', '07', '08']
det_name: ['']

det_file: './datasets/MOT20-test' # if run track.py, you need the detection files

# ------------------------------------- Detector --------------------------------------
device: cuda   # cuda or cpu
conf: 0.01
nms: 0.7
fuse: True
fp16: True
det_ckpt: './weights/bytetrack_x_mot20.tar'
exp_file: './yolox/exps/example/mot/yolox_x_mix_mot20_ch.py'

# --------------------------------------- Reid ---------------------------------------
reid_config: './fast_reid/configs/MOT20/sbs_S50.yml'
reid_weights: './weights/mot20_sbs_S50.pth'

# ------------------------------------- CMC --------------------------------------
cmc_method: file
cmc_path: './tracker/GMC_files/MOTChallenge'

# --------------------------------- Data Association ---------------------------------
pos: 0.55
cls: 0.75
match_thresh_a: 0.65
match_thresh_b: 0.65
match_thresh_c: 0.5
match_thresh_d: 0.55
track_buffer: 30
new_track_thresh: 0.7
aspect_ratio_thresh: 1.6
min_box_area: 10

# ------------------------------------- Output --------------------------------------
save_det_results: False
save_img: True
output_root: './output1'
